# Generated by Django 5.2.9 on 2025-12-03 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='completed',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='telegramuser',
            name='id',
        ),
        migrations.AddField(
            model_name='completed',
            name='status',
            field=models.CharField(choices=[('PR', 'Performs'), ('DN', 'Done')], default='PR', max_length=32),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='tasks_done',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='telegram_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
