# Generated by Django 5.2.9 on 2025-12-03 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_completed_completed_at_remove_telegramuser_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='telegramuser',
            options={'verbose_name': 'Пользователь Telegram', 'verbose_name_plural': 'Пользователи Telegram'},
        ),
        migrations.AlterField(
            model_name='completed',
            name='status',
            field=models.CharField(choices=[('PE', 'Pending'), ('DN', 'Done')], default='PE', max_length=32),
        ),
        migrations.AddConstraint(
            model_name='completed',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_user_task'),
        ),
    ]
