# Generated by Django 5.2.9 on 2025-12-10 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_telegramuser_options_alter_completed_status_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='completed',
            options={'verbose_name': 'В процессе/выполенное задание', 'verbose_name_plural': 'В процессе/выполенные задания'},
        ),
        migrations.AddField(
            model_name='task',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='task_images/', verbose_name='Картинка задания'),
        ),
    ]
