# Generated by Django 5.2.9 on 2025-12-12 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_completed_options_task_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='telegramuser',
            name='bonus_claimed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
