# Generated by Django 5.2.9 on 2025-12-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_telegramuser_bonus_claimed_telegramuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='completed',
            name='admin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='proof_image',
            field=models.ImageField(blank=True, null=True, upload_to='proof_images/'),
        ),
        migrations.AddField(
            model_name='completed',
            name='proof_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='completed',
            name='rewarded',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='completed',
            name='status',
            field=models.CharField(choices=[('PE', 'В процессе'), ('RV', 'На проверке'), ('DN', 'Принято'), ('RJ', 'Отклонено')], default='PE', max_length=2),
        ),
    ]
