# Generated by Django 5.2.11 on 2026-02-10 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_completed_admin_comment_completed_proof_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='level',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='last_push_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='locker_passed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='telegramuser',
            name='next_push_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
